os: linux
language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.7"
  - "3.6"
  - "3.8"
  - "pypy"
  - "pypy3"
# Disable version pypy, pypy3 for power support
jobs:
  exclude:
   - arch: ppc64le
     python: "pypy"
   - arch: ppc64le
     python: "pypy3"
install:
  pip install .
script:
  - pprofile --include demo --threads 0 demo/threads.py
  - pprofile --include demo --format callgrind demo/threads.py
  - pprofile --include demo --statistic .01 demo/threads.py
  - demo/embedded.py
  - pprofile --include demo demo/threads.py
  - pprofile --include demo demo/empty.py
  - pprofile --format callgrind demo/empty.py
  - pprofile --include demo --statistic .01 demo/empty.py
  - pprofile --format callgrind --zipfile source_code.zip demo/threads.py
  - pprofile --format callgrind --zipfile source_code.zip demo/empty.py
  - pprofile --exclude-syspath demo/threads.py
  - pprofile --exclude-syspath --statistic .01 demo/threads.py
  - pprofile --include demo demo/encoding.py
  - LC_CTYPE=ISO-8859-15 pprofile --include demo demo/encoding.py
  - pprofile --include demo demo/encoding.py > /dev/null
  - pprofile --include demo demo/empty.py -search
  - pprofile --include demo -- demo/empty.py -search
  - pprofile --include demo demo/recurse.py
  - pprofile --include demo demo/recurse2.py
  - pprofile --include demo demo/recurse3.py
  - pprofile --include demo demo/recurse4.py
  - pprofile --include demo demo/twocalls.py
  - pprofile --include demo demo/twocalls2.py
  - pprofile --include demo demo/the_main.py
  - pprofile --include demo demo/module_globals.py
  - pprofile --format callgrindzip --out test_threads.zip demo/threads.py && unzip -l test_threads.zip
  - pprofile --out test_threads.zip demo/threads.py && unzip -l test_threads.zip
