language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  pip install .
script:
  - pprofile --threads 0 demo/threads.py
  - pprofile --format callgrind demo/threads.py
  - pprofile --statistic .01 demo/threads.py
  - demo/embedded.py
  - pprofile demo/threads.py
  - pprofile demo/empty.py
  - pprofile --format callgrind demo/empty.py
  - pprofile --statistic .01 demo/empty.py
  - pprofile --format callgrind --zipfile source_code.zip demo/threads.py
  - pprofile --format callgrind --zipfile source_code.zip demo/empty.py
  - pprofile demo/encoding.py
  - LC_CTYPE=ISO-8859-15 pprofile demo/encoding.py
